import type { AppState } from '../types'

// Build ISO strings relative to "today" so the sample data always looks current.
function at(dayOffset: number, hour = 9, minute = 0): string {
  const d = new Date()
  d.setHours(0, 0, 0, 0)
  d.setDate(d.getDate() + dayOffset)
  d.setHours(hour, minute, 0, 0)
  return d.toISOString()
}

export function makeSeed(): AppState {
  return {
    currentUserId: 'me',
    googleConnected: false,
    venmoConnected: false,
    whatsappConnected: true,

    children: [
      { id: 'isabella', name: 'Isabella', color: 'sky', emoji: '🦄' },
      { id: 'calixta', name: 'Calixta', color: 'blush', emoji: '🌸' },
      { id: 'mateo', name: 'David', color: 'mint', emoji: '🐢' },
    ],

    members: [
      { id: 'me', name: 'You', role: 'Parent', emoji: '🦊', color: 'violet', isSelf: true },
      { id: 'coach-dave', name: 'Coach Dave', role: 'Soccer Coach', emoji: '🧢', color: 'tang' },
      { id: 'priya', name: 'Priya Shah', role: 'Homeroom Parent', emoji: '🌻', color: 'sun' },
      { id: 'ms-chen', name: 'Ms. Chen', role: 'Teacher', emoji: '🍎', color: 'sky' },
      { id: 'coach-bri', name: 'Coach Bri', role: 'Swim Coach', emoji: '🏊‍♀️', color: 'mint' },
      { id: 'alvarez', name: 'Mr. Alvarez', role: 'Scout Leader', emoji: '🏕️', color: 'violet' },
      { id: 'jenna', name: 'Jenna M.', role: 'Parent', emoji: '💐', color: 'blush' },
      { id: 'marcus', name: 'Marcus T.', role: 'Parent', emoji: '⚽', color: 'sky' },
      { id: 'lena', name: 'Lena K.', role: 'Parent', emoji: '🎨', color: 'sun' },
      { id: 'office', name: 'Lincoln Office', role: 'School', emoji: '🏫', color: 'blush' },
    ],

    groups: [
      {
        id: 'soccer',
        name: 'Westside United U10',
        category: 'Soccer',
        color: 'tang',
        emoji: '⚽',
        childIds: ['calixta'],
        memberIds: ['me', 'coach-dave', 'jenna', 'marcus', 'lena'],
      },
      {
        id: 'class-isabella',
        name: "Ms. Chen's 3rd Grade",
        category: 'School',
        color: 'sky',
        emoji: '📚',
        childIds: ['isabella'],
        memberIds: ['me', 'ms-chen', 'priya', 'jenna', 'lena'],
      },
      {
        id: 'swim',
        name: 'Riverside Swim Team',
        category: 'Swim',
        color: 'mint',
        emoji: '🏊',
        childIds: ['mateo'],
        memberIds: ['me', 'coach-bri', 'marcus'],
      },
      {
        id: 'scouts',
        name: 'Troop 402 Scouts',
        category: 'Scouts',
        color: 'violet',
        emoji: '🏕️',
        childIds: ['mateo'],
        memberIds: ['me', 'alvarez', 'lena'],
      },
      {
        id: 'pta',
        name: 'Lincoln Elementary PTA',
        category: 'School',
        color: 'blush',
        emoji: '🏫',
        childIds: ['isabella', 'calixta', 'mateo'],
        memberIds: ['me', 'office', 'priya', 'jenna', 'marcus', 'lena'],
      },
    ],

    events: [
      {
        id: 'ev-1',
        groupId: 'soccer',
        childId: 'calixta',
        title: 'Home game vs. Northgate FC',
        date: at(2, 10, 0),
        location: 'Field 4, Westside Park',
        note: 'Arrive 30 min early for warm-ups.',
        addedToGoogle: false,
        createdFromMessageId: 'm-soccer-3',
      },
      {
        id: 'ev-2',
        groupId: 'class-isabella',
        childId: 'isabella',
        title: 'Field trip: Science Museum',
        date: at(6, 8, 30),
        location: 'Meet at school drop-off',
        note: 'Signed permission slip required.',
        addedToGoogle: false,
      },
      {
        id: 'ev-3',
        groupId: 'swim',
        childId: 'mateo',
        title: 'Swim meet — Regionals',
        date: at(9, 9, 0),
        location: 'Riverside Aquatic Center',
        addedToGoogle: false,
      },
      {
        id: 'ev-4',
        groupId: 'scouts',
        childId: 'mateo',
        title: 'Overnight camping trip',
        date: at(13, 16, 0),
        location: 'Cedar Ridge Campground',
        note: 'Packing list in the group.',
        addedToGoogle: false,
      },
      {
        id: 'ev-5',
        groupId: 'pta',
        title: 'PTA meeting + fall fundraiser kickoff',
        date: at(4, 18, 30),
        location: 'Lincoln cafeteria',
        addedToGoogle: false,
      },
      {
        id: 'ev-6',
        groupId: 'soccer',
        childId: 'calixta',
        title: 'Practice',
        date: at(1, 17, 0),
        location: 'Field 2, Westside Park',
        addedToGoogle: false,
      },
    ],

    tasks: [
      {
        id: 't-1',
        groupId: 'soccer',
        childId: 'calixta',
        title: 'Bring a RED shirt for team photos',
        dueDate: at(2, 9, 30),
        done: false,
        priority: 'high',
        assigneeIds: ['me'],
        createdFromMessageId: 'm-soccer-5',
      },
      {
        id: 't-2',
        groupId: 'soccer',
        childId: 'calixta',
        title: 'Pay season jersey fee',
        dueDate: at(3),
        done: false,
        priority: 'high',
        assigneeIds: ['me'],
        payment: { amount: 45, recipient: 'Coach Dave', method: 'venmo', paid: false },
      },
      {
        id: 't-3',
        groupId: 'class-isabella',
        childId: 'isabella',
        title: 'Sign & return museum permission slip',
        dueDate: at(5),
        done: false,
        priority: 'high',
        assigneeIds: ['me'],
        createdFromMessageId: 'm-class-2',
      },
      {
        id: 't-5',
        groupId: 'swim',
        childId: 'mateo',
        title: 'Order team swim cap',
        dueDate: at(4),
        done: false,
        priority: 'medium',
        assigneeIds: ['me'],
        payment: { amount: 18, recipient: 'Coach Bri', method: 'cashapp', paid: false },
      },
      {
        id: 't-6',
        groupId: 'scouts',
        childId: 'mateo',
        title: 'Pack sleeping bag & headlamp for camp',
        dueDate: at(12),
        done: false,
        priority: 'medium',
        assigneeIds: ['me'],
      },
      {
        id: 't-7',
        groupId: 'scouts',
        childId: 'mateo',
        title: 'Camp trip fee',
        dueDate: at(6),
        done: false,
        priority: 'high',
        assigneeIds: ['me'],
        payment: { amount: 30, recipient: 'Mr. Alvarez', method: 'venmo', paid: false },
      },
      {
        id: 't-8',
        groupId: 'pta',
        title: 'Volunteer slot: fundraiser bake sale',
        dueDate: at(4, 12, 0),
        done: false,
        priority: 'low',
        assigneeIds: ['me'],
      },
      {
        id: 't-9',
        groupId: 'soccer',
        childId: 'calixta',
        title: 'Bring orange slices for Saturday',
        dueDate: at(-1),
        done: false,
        priority: 'medium',
        assigneeIds: ['me'],
      },
      {
        id: 't-10',
        groupId: 'class-isabella',
        childId: 'isabella',
        title: 'Read-a-thon pledge form',
        dueDate: at(-2),
        done: false,
        priority: 'low',
        assigneeIds: ['me'],
      },
      {
        id: 't-11',
        groupId: 'swim',
        childId: 'mateo',
        title: 'RSVP for team pasta dinner',
        dueDate: at(1),
        done: true,
        priority: 'low',
        assigneeIds: ['me'],
      },
    ],

    signups: [
      {
        id: 'su-1',
        groupId: 'class-isabella',
        childId: 'isabella',
        title: "Isabella's class Halloween party",
        note: 'Party is Friday afternoon 🎃 Grab whatever you can — thank you!',
        dueDate: at(4, 12, 0),
        createdById: 'priya',
        createdAt: at(-2, 11, 12),
        slots: [
          { id: 'su1-a', label: '12 juice boxes', qty: 2, claims: [{ memberId: 'lena' }] },
          { id: 'su1-b', label: 'Napkins + paper plates', qty: 1, claims: [{ memberId: 'jenna' }] },
          { id: 'su1-c', label: 'Cupcakes (2 dozen)', qty: 2, claims: [] },
          { id: 'su1-d', label: 'Fruit or veggie tray', qty: 1, claims: [] },
          { id: 'su1-e', label: 'Halloween decorations', qty: 1, claims: [] },
        ],
      },
    ],

    messages: [
      // Soccer
      {
        id: 'm-soccer-1',
        groupId: 'soccer',
        senderId: 'coach-dave',
        text: 'Hi Westside families! Great practice today. A few reminders coming up for the week. 👇',
        at: at(-2, 16, 10),
      },
      {
        id: 'm-soccer-2',
        groupId: 'soccer',
        senderId: 'jenna',
        text: 'Thanks Coach! Is practice still at Field 2 tomorrow?',
        at: at(-2, 16, 18),
      },
      {
        id: 'm-soccer-3',
        groupId: 'soccer',
        senderId: 'coach-dave',
        text: 'Yes — practice tomorrow 5pm at Field 2. And our home game vs Northgate is Saturday 10am, Field 4. Please arrive 30 min early.',
        at: at(-2, 16, 22),
        linkedEventId: 'ev-1',
        pinned: true,
      },
      {
        id: 'm-soccer-4',
        groupId: 'soccer',
        senderId: 'marcus',
        text: 'Got it, see everyone there!',
        at: at(-2, 16, 40),
      },
      {
        id: 'm-soccer-5',
        groupId: 'soccer',
        senderId: 'coach-dave',
        text: 'One more — team photos before the game. Everyone please bring a RED shirt by Saturday. 📸',
        at: at(-1, 9, 5),
        linkedTaskId: 't-1',
      },
      {
        id: 'm-soccer-6',
        groupId: 'soccer',
        senderId: 'coach-dave',
        text: 'And jersey fees ($45) are due this week — you can Venmo me. Thanks all!',
        at: at(-1, 9, 7),
        linkedTaskId: 't-2',
      },

      // Class
      {
        id: 'm-class-1',
        groupId: 'class-isabella',
        senderId: 'ms-chen',
        text: 'Hello families! Our Science Museum field trip is next week. Details to follow.',
        at: at(-3, 14, 0),
      },
      {
        id: 'm-class-2',
        groupId: 'class-isabella',
        senderId: 'ms-chen',
        text: 'Permission slips went home in backpacks today. Please sign and return by this Friday so your child can attend. 🙏',
        at: at(-3, 14, 3),
        linkedTaskId: 't-3',
      },
      {
        id: 'm-class-3',
        groupId: 'class-isabella',
        senderId: 'priya',
        text: "I'm organizing the class party! I'll post a sign-up for snacks shortly.",
        at: at(-2, 11, 0),
      },
      {
        id: 'm-class-4',
        groupId: 'class-isabella',
        senderId: 'priya',
        text: "Here's the sign-up for the class party 🎃 — grab whatever you can bring!",
        at: at(-2, 11, 12),
        linkedSignupId: 'su-1',
      },
      {
        id: 'm-class-5',
        groupId: 'class-isabella',
        senderId: 'me',
        text: 'Amazing, thank you for organizing Priya! 🙌',
        at: at(-2, 11, 30),
      },

      // Swim
      {
        id: 'm-swim-1',
        groupId: 'swim',
        senderId: 'coach-bri',
        text: 'Regionals are a week out! Full team, please be at Riverside by 9am that morning.',
        at: at(-1, 8, 0),
        linkedEventId: 'ev-3',
      },
      {
        id: 'm-swim-2',
        groupId: 'swim',
        senderId: 'coach-bri',
        text: 'New team caps are in — $18 each, Cash App works. Let me know sizes.',
        at: at(-1, 8, 3),
        linkedTaskId: 't-5',
      },

      // Scouts
      {
        id: 'm-scouts-1',
        groupId: 'scouts',
        senderId: 'alvarez',
        text: 'Troop 402 — overnight camping trip is set for next weekend at Cedar Ridge. 🏕️',
        at: at(-2, 19, 0),
        linkedEventId: 'ev-4',
      },
      {
        id: 'm-scouts-2',
        groupId: 'scouts',
        senderId: 'alvarez',
        text: 'Trip fee is $30 (covers site + meals), due before we leave. Packing list: sleeping bag, headlamp, warm layers, water bottle.',
        at: at(-2, 19, 4),
        linkedTaskId: 't-7',
      },

      // PTA
      {
        id: 'm-pta-1',
        groupId: 'pta',
        senderId: 'office',
        text: 'Reminder: PTA meeting Thursday 6:30pm in the cafeteria. We kick off the fall fundraiser!',
        at: at(-1, 10, 0),
        linkedEventId: 'ev-5',
      },
      {
        id: 'm-pta-2',
        groupId: 'pta',
        senderId: 'priya',
        text: 'We need a few volunteers for the bake sale table. Grab a slot if you can!',
        at: at(-1, 10, 20),
        linkedTaskId: 't-8',
      },
    ],
  }
}
