import type { AppState } from '../types'

// Build ISO strings relative to "today" so the sample data always looks current.
function at(dayOffset: number, hour = 9, minute = 0): string {
  const d = new Date()
  d.setHours(0, 0, 0, 0)
  d.setDate(d.getDate() + dayOffset)
  d.setHours(hour, minute, 0, 0)
  return d.toISOString()
}

// Tiny inline SVG "photos" so the Files gallery has sample images.
function img(label: string, bg: string): string {
  const svg = `<svg xmlns='http://www.w3.org/2000/svg' width='400' height='300'><rect width='400' height='300' fill='${bg}'/><text x='200' y='160' font-family='sans-serif' font-size='30' font-weight='bold' fill='white' text-anchor='middle'>${label}</text></svg>`
  return `data:image/svg+xml,${encodeURIComponent(svg)}`
}

export function makeSeed(): AppState {
  return {
    currentUserId: 'me',
    googleConnected: false,
    venmoConnected: false,
    whatsappConnected: true,
    translateTo: '',
    // Your own notification prefs per group (unset = on). Swim digest starts off
    // to show a mixed state.
    notify: {
      swim: { reminders: true, digest: false },
    },

    // Messages "forwarded" to your Village number/email, waiting to be turned
    // into tasks or events. (In the real app these arrive from WhatsApp/SMS/email.)
    forwards: [
      {
        id: 'fwd-1',
        source: 'whatsapp',
        text: "Hi everyone! Don't forget it's Spirit Day this Friday — kids should wear school colors. 💙💛",
        at: at(0, 8, 15),
      },
      {
        id: 'fwd-2',
        source: 'sms',
        text: 'Reminder from Riverside Swim: goggles order forms + $12 due Monday.',
        at: at(-1, 17, 40),
      },
    ],

    children: [
      { id: 'isabella', name: 'Isabella', color: 'sky', emoji: '🦄' },
      { id: 'calixta', name: 'Calixta', color: 'blush', emoji: '🌸' },
      { id: 'mateo', name: 'David', color: 'mint', emoji: '🐢' },
    ],

    members: [
      { id: 'me', name: 'You', role: 'Parent', emoji: '🦊', color: 'violet', phone: '+1 (415) 555-0100', handles: { venmo: '@sam-ortiz', cashapp: '$SamOrtiz', zelle: 'sam@email.com' }, isSelf: true },
      { id: 'coach-dave', name: 'Coach Dave', role: 'Soccer Coach', emoji: '🧢', color: 'tang', phone: '+1 (415) 555-0142', handles: { venmo: '@coach-dave', zelle: 'dave.coach@email.com' } },
      { id: 'priya', name: 'Priya Shah', role: 'Homeroom Parent', emoji: '🌻', color: 'sun', phone: '+1 (415) 555-0177' },
      { id: 'ms-chen', name: 'Ms. Chen', role: 'Teacher', emoji: '🍎', color: 'sky', phone: '+1 (415) 555-0110' },
      { id: 'coach-bri', name: 'Coach Bri', role: 'Swim Coach', emoji: '🏊‍♀️', color: 'mint', phone: '+1 (415) 555-0155', handles: { cashapp: '$CoachBri', venmo: '@coachbri' } },
      { id: 'alvarez', name: 'Mr. Alvarez', role: 'Scout Leader', emoji: '🏕️', color: 'violet', phone: '+1 (415) 555-0188', handles: { venmo: '@troop402' } },
      { id: 'jenna', name: 'Jenna M.', role: 'Parent', emoji: '💐', color: 'blush', phone: '+1 (415) 555-0121' },
      { id: 'marcus', name: 'Marcus T.', role: 'Parent', emoji: '⚽', color: 'sky', phone: '+1 (415) 555-0133' },
      { id: 'lena', name: 'Lena K.', role: 'Parent', emoji: '🎨', color: 'sun', phone: '+1 (415) 555-0166' },
      { id: 'rosa', name: 'Grandma Rosa', role: 'Caregiver', emoji: '👵', color: 'tang', phone: '+1 (415) 555-0190' },
      { id: 'office', name: 'Lincoln Office', role: 'School', emoji: '🏫', color: 'blush', phone: '+1 (415) 555-0101' },
    ],

    groups: [
      {
        id: 'soccer',
        name: 'Westside United U10',
        category: 'Soccer',
        color: 'tang',
        emoji: '⚽',
        childIds: ['calixta'],
        joinCode: 'SOCCER-4B2',
        announcementsOnly: false,
        members: [
          { memberId: 'coach-dave', role: 'admin', relationship: 'Coach' },
          { memberId: 'me', role: 'admin', childName: 'Calixta', relationship: 'Parent' },
          { memberId: 'jenna', role: 'member', childName: 'Ella', relationship: 'Mom' },
          { memberId: 'marcus', role: 'member', childName: 'Liam', relationship: 'Dad' },
          { memberId: 'lena', role: 'member', childName: 'Mia', relationship: 'Mom' },
        ],
      },
      {
        id: 'class-isabella',
        name: "Ms. Chen's 3rd Grade",
        category: 'School',
        color: 'sky',
        emoji: '📚',
        childIds: ['isabella'],
        joinCode: 'MSCHEN-3G',
        announcementsOnly: false,
        members: [
          { memberId: 'ms-chen', role: 'admin', relationship: 'Teacher' },
          { memberId: 'priya', role: 'admin', childName: 'Aria', relationship: 'Mom' },
          { memberId: 'me', role: 'member', childName: 'Isabella', relationship: 'Parent' },
          { memberId: 'jenna', role: 'member', childName: 'Ella', relationship: 'Mom' },
          { memberId: 'lena', role: 'member', childName: 'Mia', relationship: 'Mom' },
        ],
      },
      {
        id: 'swim',
        name: 'Riverside Swim Team',
        category: 'Swim',
        color: 'mint',
        emoji: '🏊',
        childIds: ['mateo'],
        joinCode: 'SWIM-RIV',
        announcementsOnly: false,
        members: [
          { memberId: 'coach-bri', role: 'admin', relationship: 'Coach' },
          { memberId: 'me', role: 'member', childName: 'David', relationship: 'Parent' },
          { memberId: 'rosa', role: 'member', childName: 'David', relationship: 'Grandma' },
          { memberId: 'marcus', role: 'member', childName: 'Liam', relationship: 'Dad' },
        ],
      },
      {
        id: 'scouts',
        name: 'Troop 402 Scouts',
        category: 'Scouts',
        color: 'violet',
        emoji: '🏕️',
        childIds: ['mateo'],
        joinCode: 'TROOP-402',
        announcementsOnly: false,
        members: [
          { memberId: 'alvarez', role: 'admin', relationship: 'Leader' },
          { memberId: 'me', role: 'member', childName: 'David', relationship: 'Parent' },
          { memberId: 'lena', role: 'member', childName: 'Mia', relationship: 'Mom' },
        ],
      },
      {
        id: 'pta',
        name: 'Lincoln Elementary PTA',
        category: 'School',
        color: 'blush',
        emoji: '🏫',
        childIds: ['isabella', 'calixta', 'mateo'],
        joinCode: 'LINCOLN-PTA',
        announcementsOnly: true,
        members: [
          { memberId: 'office', role: 'admin', relationship: 'School' },
          { memberId: 'priya', role: 'admin', childName: 'Aria', relationship: 'Mom' },
          { memberId: 'me', role: 'member', childName: 'Isabella', relationship: 'Parent' },
          { memberId: 'jenna', role: 'member', childName: 'Ella', relationship: 'Mom' },
          { memberId: 'marcus', role: 'member', childName: 'Liam', relationship: 'Dad' },
          { memberId: 'lena', role: 'member', childName: 'Mia', relationship: 'Mom' },
        ],
      },
      // Discoverable group the current user has NOT joined yet — try code CHESS-42.
      {
        id: 'chess',
        name: 'Lincoln Chess Club',
        category: 'Club',
        color: 'sun',
        emoji: '♟️',
        childIds: [],
        joinCode: 'CHESS-42',
        announcementsOnly: false,
        members: [
          { memberId: 'lena', role: 'admin', relationship: 'Coordinator' },
          { memberId: 'jenna', role: 'member', childName: 'Ella', relationship: 'Mom' },
        ],
      },
    ],

    polls: [
      {
        id: 'poll-2',
        groupId: 'soccer',
        question: 'Team warm-up jacket color?',
        multi: false,
        createdById: 'coach-dave',
        options: [
          { id: 'p2a', label: 'Red', votes: ['me', 'jenna'], amount: 28 },
          { id: 'p2b', label: 'Navy', votes: ['marcus'], amount: 28 },
          { id: 'p2c', label: 'Black (premium)', votes: [], amount: 32 },
        ],
      },
      {
        id: 'poll-1',
        groupId: 'pta',
        question: 'Fall fundraiser theme?',
        multi: false,
        createdById: 'office',
        options: [
          { id: 'po-a', label: 'Fall Carnival', votes: ['priya', 'jenna'] },
          { id: 'po-b', label: 'Movie Night', votes: ['marcus'] },
          { id: 'po-c', label: 'Family Fun Run', votes: ['lena'] },
        ],
      },
    ],

    collections: [
      {
        id: 'col-1',
        groupId: 'soccer',
        childName: 'the team',
        title: 'End-of-season coach gift 🎁',
        note: 'Chipping in for Coach Dave — suggested $20, no pressure!',
        suggested: 20,
        acceptedMethods: ['venmo', 'zelle'],
        handles: { venmo: '@jenna-m', zelle: 'jenna.m@email.com' },
        recipient: 'Jenna (team parent)',
        createdById: 'jenna',
        contributions: [
          { memberId: 'jenna', amount: 20 },
          { memberId: 'lena', amount: 25 },
        ],
      },
    ],

    events: [
      {
        id: 'ev-1',
        groupId: 'soccer',
        childId: 'calixta',
        title: 'Home game vs. Northgate FC',
        date: at(2, 10, 0),
        location: 'Field 4, Westside Park',
        note: 'Arrive 30 min early for warm-ups.',
        addedToGoogle: false,
        createdById: 'coach-dave',
        createdFromMessageId: 'm-soccer-3',
        rsvps: { me: 'going', jenna: 'going', marcus: 'maybe', lena: 'going' },
        carpoolOffers: [{ memberId: 'marcus', seats: 2 }],
        carpoolRequests: ['jenna'],
      },
      {
        id: 'ev-2',
        groupId: 'class-isabella',
        childId: 'isabella',
        title: 'Field trip: Science Museum',
        date: at(6, 8, 30),
        location: 'Meet at school drop-off',
        note: 'Signed permission slip required.',
        addedToGoogle: false,
        createdById: 'ms-chen',
      },
      {
        id: 'ev-3',
        groupId: 'swim',
        childId: 'mateo',
        title: 'Swim meet — Regionals',
        date: at(9, 9, 0),
        location: 'Riverside Aquatic Center',
        addedToGoogle: false,
        createdById: 'coach-bri',
        rsvps: { me: 'going', marcus: 'going' },
      },
      {
        id: 'ev-4',
        groupId: 'scouts',
        childId: 'mateo',
        title: 'Overnight camping trip',
        date: at(13, 16, 0),
        location: 'Cedar Ridge Campground',
        note: 'Packing list in the group.',
        addedToGoogle: false,
        createdById: 'alvarez',
      },
      {
        id: 'ev-5',
        groupId: 'pta',
        title: 'PTA meeting + fall fundraiser kickoff',
        date: at(4, 18, 30),
        location: 'Lincoln cafeteria',
        addedToGoogle: false,
        createdById: 'office',
      },
      {
        id: 'ev-6',
        groupId: 'soccer',
        childId: 'calixta',
        title: 'Practice',
        date: at(1, 17, 0),
        location: 'Field 2, Westside Park',
        addedToGoogle: false,
        createdById: 'coach-dave',
        recurrence: 'weekly',
      },
    ],

    tasks: [
      {
        id: 't-1',
        groupId: 'soccer',
        childId: 'calixta',
        title: 'Bring a RED shirt for team photos',
        dueDate: at(2, 9, 30),
        done: false,
        priority: 'high',
        assigneeIds: ['me'],
        createdById: 'coach-dave',
        createdFromMessageId: 'm-soccer-5',
      },
      {
        id: 't-2',
        groupId: 'soccer',
        childId: 'calixta',
        title: 'Pay season jersey fee',
        dueDate: at(3),
        done: false,
        priority: 'high',
        assigneeIds: ['me'],
        createdById: 'coach-dave',
        payment: { amount: 45, recipient: 'Coach Dave', methods: ['venmo', 'zelle'], handles: { venmo: '@coach-dave', zelle: 'dave.coach@email.com' }, paid: false },
      },
      {
        id: 't-3',
        groupId: 'class-isabella',
        childId: 'isabella',
        title: 'Sign & return museum permission slip',
        dueDate: at(5),
        done: false,
        priority: 'high',
        assigneeIds: ['me'],
        createdById: 'ms-chen',
        createdFromMessageId: 'm-class-2',
      },
      {
        id: 't-5',
        groupId: 'swim',
        childId: 'mateo',
        title: 'Order team swim cap',
        dueDate: at(4),
        done: false,
        priority: 'medium',
        assigneeIds: ['me'],
        createdById: 'coach-bri',
        payment: { amount: 18, recipient: 'Coach Bri', methods: ['cashapp', 'venmo'], handles: { cashapp: '$CoachBri', venmo: '@coachbri' }, paid: false },
      },
      {
        id: 't-6',
        groupId: 'scouts',
        childId: 'mateo',
        title: 'Pack sleeping bag & headlamp for camp',
        dueDate: at(12),
        done: false,
        priority: 'medium',
        assigneeIds: ['me', 'rosa'],
        createdById: 'alvarez',
      },
      {
        id: 't-7',
        groupId: 'scouts',
        childId: 'mateo',
        title: 'Camp trip fee',
        dueDate: at(6),
        done: false,
        priority: 'high',
        assigneeIds: ['me'],
        createdById: 'alvarez',
        payment: { amount: 30, recipient: 'Mr. Alvarez', methods: ['venmo'], handles: { venmo: '@troop402' }, paid: false },
      },
      {
        id: 't-8',
        groupId: 'pta',
        title: 'Volunteer slot: fundraiser bake sale',
        dueDate: at(4, 12, 0),
        done: false,
        priority: 'low',
        assigneeIds: ['me'],
        createdById: 'priya',
      },
      {
        id: 't-9',
        groupId: 'soccer',
        childId: 'calixta',
        title: 'Bring orange slices for Saturday',
        dueDate: at(-1),
        done: false,
        priority: 'medium',
        assigneeIds: ['me'],
        createdById: 'coach-dave',
      },
      {
        id: 't-10',
        groupId: 'class-isabella',
        childId: 'isabella',
        title: 'Read-a-thon pledge form',
        dueDate: at(-2),
        done: false,
        priority: 'low',
        assigneeIds: ['me'],
        createdById: 'ms-chen',
      },
      {
        id: 't-11',
        groupId: 'swim',
        childId: 'mateo',
        title: 'RSVP for team pasta dinner',
        dueDate: at(1),
        done: true,
        priority: 'low',
        assigneeIds: ['me'],
        createdById: 'coach-bri',
      },
    ],

    signups: [
      {
        id: 'su-1',
        groupId: 'class-isabella',
        childId: 'isabella',
        title: "Isabella's class Halloween party",
        note: 'Party is Friday afternoon 🎃 Grab whatever you can — thank you!',
        dueDate: at(4, 12, 0),
        createdById: 'priya',
        createdAt: at(-2, 11, 12),
        slots: [
          { id: 'su1-a', label: '12 juice boxes', qty: 2, claims: [{ memberId: 'lena' }] },
          { id: 'su1-b', label: 'Napkins + paper plates', qty: 1, claims: [{ memberId: 'jenna' }] },
          { id: 'su1-c', label: 'Cupcakes (2 dozen)', qty: 2, claims: [] },
          { id: 'su1-d', label: 'Fruit or veggie tray', qty: 1, claims: [] },
          { id: 'su1-e', label: 'Halloween decorations', qty: 1, claims: [] },
        ],
      },
    ],

    messages: [
      // Soccer
      {
        id: 'm-soccer-1',
        groupId: 'soccer',
        senderId: 'coach-dave',
        text: 'Hi Westside families! Great practice today. A few reminders coming up for the week. 👇',
        at: at(-2, 16, 10),
      },
      {
        id: 'm-soccer-2',
        groupId: 'soccer',
        senderId: 'jenna',
        text: 'Thanks Coach! Is practice still at Field 2 tomorrow?',
        at: at(-2, 16, 18),
      },
      {
        id: 'm-soccer-3',
        groupId: 'soccer',
        senderId: 'coach-dave',
        text: 'Yes — practice tomorrow 5pm at Field 2. And our home game vs Northgate is Saturday 10am, Field 4. Please arrive 30 min early.',
        at: at(-2, 16, 22),
        linkedEventId: 'ev-1',
        pinned: true,
      },
      {
        id: 'm-soccer-4',
        groupId: 'soccer',
        senderId: 'marcus',
        text: 'Got it, see everyone there!',
        at: at(-2, 16, 40),
        reactions: { '👍': ['coach-dave', 'jenna'] },
      },
      {
        id: 'm-soccer-5',
        groupId: 'soccer',
        senderId: 'coach-dave',
        text: 'One more — team photos before the game. Everyone please bring a RED shirt by Saturday. 📸',
        at: at(-1, 9, 5),
        linkedTaskId: 't-1',
        reactions: { '👍': ['jenna', 'marcus'], '❤️': ['lena'] },
      },
      {
        id: 'm-soccer-6',
        groupId: 'soccer',
        senderId: 'coach-dave',
        text: 'And jersey fees ($45) are due this week — you can Venmo me. Thanks all!',
        at: at(-1, 9, 7),
        linkedTaskId: 't-2',
      },
      {
        id: 'm-soccer-photo',
        groupId: 'soccer',
        senderId: 'coach-dave',
        text: 'Team photo from last week — look at these champs! 📸',
        at: at(-1, 11, 30),
        attachment: { name: 'team-photo.jpg', kind: 'image', dataUrl: img('⚽ Team Photo', '#F07E3E') },
        reactions: { '❤️': ['jenna', 'lena', 'marcus'] },
      },
      {
        id: 'm-soccer-jacket',
        groupId: 'soccer',
        senderId: 'coach-dave',
        text: "Let's vote on the team warm-up jacket color — each has a one-time cost, we'll collect once we pick. 🧥",
        at: at(-1, 11, 45),
        linkedPollId: 'poll-2',
      },
      {
        id: 'm-soccer-collect',
        groupId: 'soccer',
        senderId: 'jenna',
        text: "Parents — let's chip in for an end-of-season gift for Coach Dave! 🎁",
        at: at(-1, 12, 0),
        linkedCollectionId: 'col-1',
      },

      // Class
      {
        id: 'm-class-1',
        groupId: 'class-isabella',
        senderId: 'ms-chen',
        text: 'Hello families! Our Science Museum field trip is next week. Details to follow.',
        at: at(-3, 14, 0),
      },
      {
        id: 'm-class-2',
        groupId: 'class-isabella',
        senderId: 'ms-chen',
        text: 'Permission slips went home in backpacks today. Please sign and return by Friday so your child can attend. 🙏 Please tap "Got it" so I know you saw this.',
        at: at(-3, 14, 3),
        linkedTaskId: 't-3',
        requireAck: true,
        acks: ['jenna', 'lena'],
        attachment: { name: 'Museum Permission Slip.pdf', kind: 'pdf' },
      },
      {
        id: 'm-class-6',
        groupId: 'class-isabella',
        senderId: 'ms-chen',
        text: 'Field trip supply list is attached — please review before Friday.',
        at: at(-3, 14, 6),
        attachment: { name: 'Field trip supply list.pdf', kind: 'pdf' },
      },
      {
        id: 'm-class-3',
        groupId: 'class-isabella',
        senderId: 'priya',
        text: "I'm organizing the class party! Sign-up and a quick poll below.",
        at: at(-2, 11, 0),
      },
      {
        id: 'm-class-4',
        groupId: 'class-isabella',
        senderId: 'priya',
        text: "Here's the sign-up for the class party 🎃 — grab whatever you can bring!",
        at: at(-2, 11, 12),
        linkedSignupId: 'su-1',
      },
      {
        id: 'm-class-5',
        groupId: 'class-isabella',
        senderId: 'me',
        text: 'Amazing, thank you for organizing Priya! 🙌',
        at: at(-2, 11, 30),
        reactions: { '❤️': ['priya'] },
      },

      // Swim
      {
        id: 'm-swim-1',
        groupId: 'swim',
        senderId: 'coach-bri',
        text: 'Regionals are a week out! Full team, please be at Riverside by 9am that morning.',
        at: at(-1, 8, 0),
        linkedEventId: 'ev-3',
      },
      {
        id: 'm-swim-2',
        groupId: 'swim',
        senderId: 'coach-bri',
        text: 'New team caps are in — $18 each, Cash App works. Let me know sizes.',
        at: at(-1, 8, 3),
        linkedTaskId: 't-5',
      },
      {
        id: 'm-swim-3',
        groupId: 'swim',
        senderId: 'rosa',
        text: "I'll take David to the meet if you're working that morning! 💙",
        at: at(-1, 8, 20),
        reactions: { '🙏': ['me'] },
      },

      // Scouts
      {
        id: 'm-scouts-1',
        groupId: 'scouts',
        senderId: 'alvarez',
        text: 'Troop 402 — overnight camping trip is set for next weekend at Cedar Ridge. 🏕️',
        at: at(-2, 19, 0),
        linkedEventId: 'ev-4',
      },
      {
        id: 'm-scouts-2',
        groupId: 'scouts',
        senderId: 'alvarez',
        text: 'Trip fee is $30 (covers site + meals), due before we leave. Packing list: sleeping bag, headlamp, warm layers, water bottle.',
        at: at(-2, 19, 4),
        linkedTaskId: 't-7',
      },

      // PTA
      {
        id: 'm-pta-1',
        groupId: 'pta',
        senderId: 'office',
        text: 'Reminder: PTA meeting Thursday 6:30pm in the cafeteria. We kick off the fall fundraiser!',
        at: at(-1, 10, 0),
        linkedEventId: 'ev-5',
      },
      {
        id: 'm-pta-poll',
        groupId: 'pta',
        senderId: 'office',
        text: "Let's vote on this year's fundraiser theme 🎉",
        at: at(-1, 10, 5),
        linkedPollId: 'poll-1',
      },
      {
        id: 'm-pta-flyer',
        groupId: 'pta',
        senderId: 'office',
        text: 'Fundraiser flyer — please print & share with your networks!',
        at: at(-1, 10, 10),
        attachment: { name: 'fundraiser-flyer.png', kind: 'image', dataUrl: img('🎉 Fundraiser', '#E45FCF') },
      },
      {
        id: 'm-pta-2',
        groupId: 'pta',
        senderId: 'priya',
        text: 'We need a few volunteers for the bake sale table. Grab a slot if you can!',
        at: at(-1, 10, 20),
        linkedTaskId: 't-8',
      },
    ],
  }
}
